[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "c3fb6c59cbc22d36643ab66b0bb405e5f72cf526"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "263be89e2b730cc13f290f8eba949680ce983ce2951ecbf38d5853cf03a496be"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-apple-darwin-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "abfd26229e79721ba34acc61d3f902655e413caa"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "fde4cff4f53f6d81ccc0a10f30785c188bf00e337071c293ef48f244d11feaca"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-linux-gnu-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "120edb04e8793822232aec254fd853c3fd73e0f6"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "5394c1297f3c8782009c08a2c4476831e5e7ebe5a93ff8b8c880ac0e071b307a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-w64-mingw32-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "15d0fa8d50d49a518aa37a6567441b243c0d41d3"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "a2681257b21a3946323e9ef078dcd8f09a84469ce00e25ac5583bfb93d4b217a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-apple-darwin-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "ec2c5ac1127969d1a2dc2204972587b045f1bd1d"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "590ab60fe5691b6699254f3464d7d64f4c28acba7d74080740a2fd68a2aad475"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-linux-gnu-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "62fd7cb750233da012252650b69d79afe383ff49"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "18919a2c709580dbe2cf60bdc7931083424c97c251c17347bfef63a35fd7915a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-w64-mingw32-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "66ef4431dd0162276493137f3f43be302248748c"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "1ceb7784dea088f71f2eb1bf8a90566c78230f8392cca91f5737116133796a31"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-apple-darwin-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "0b698ea82a815b0551385d80053449347c679d2e"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "c666d13eccbf04918834371627ef097f9a61cbc4208c2b6739ba3c7de70e40ad"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-linux-gnu-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "5dc75d2507d2886ee5c309d7a9e4c2ecd23d0675"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "499c37fd49d1010b6fc65b7f3a6e9d9edf2b2a8978e7d87508c958c9042fe2c5"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-w64-mingw32-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "4b868d7c2e5d15c5d1edc47503b659ef0e70fc28"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "e98270ef285f25f7ff653aabcf687b60b154d8ffd5bc38a1ce66bd60ac0e2327"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-apple-darwin-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "1922ae6c36b5f17526a45d81be721f0765d10db9"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "298ba1f4d89cdfe57c4c18cb431ff22759e45441e617d330f763eaa7523395f8"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-linux-gnu-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "a3cdc71ed971c74d70629e78ac6eae95f0187d4a"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "3035b8a306e0f26b4f2bbe38e8f9820e7c5ac055858c3a879389e65f1845942b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-w64-mingw32-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "aarch64"
cuda = "10.2"
git-tree-sha1 = "1ea4158d95b79afb92fea68f9655ce2193dfb556"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "4a0c0ab997b9c2c9e3b3cd8e52d86ae4c54d3f858c656cda3eae4984a504d3de"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.aarch64-linux-gnu-cuda+10.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "a2c855ae291a38cce572b1d0f5051d972c735c48"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "5b1ac9a64455508b46f5cc82a7866c06b63ced6f6105d685d0915dd7977b3a11"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-linux-gnu-cuda+10.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "f7c05a5c19cc9d2888150993f03b30e2169360f9"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "e410cfee5eb384ae2fb0391b157ffc2b5eb4fa7cec8c3da02f11f09247b7b2b7"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-w64-mingw32-cuda+10.2.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.0"
git-tree-sha1 = "31cc3bec5ae4717451c6f1bcfe7a84e553ac11d0"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "0a3c6b6af13ac23ce76adb7b190e361b081f9bfa5c5d349ec6f8778349fdb87e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.powerpc64le-linux-gnu-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "7c3907ba179d2fe11d272064ca9e1f3abb06bd59"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "11f2e012d9e6dc1bd6c038563b827d99a1b8db88509d0172777b61f9e91260db"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "69e5251f686d2774a02bf48aeea04fc1ebe32ada"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "7b66a706f71657cdaef1d9ff6dcb7a21e0f6c888c53355f78842fc63d1f18c93"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-w64-mingw32-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.1"
git-tree-sha1 = "68662b5678e1b335e327647957459046e480bc96"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "962071233693633ae892eacb8bcc8ed9802d4af054ba5c3ab19ae8e323a10255"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.powerpc64le-linux-gnu-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "97e9c2fd5fdb8cd5eb0fc9da00188a23ab5ed010"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "1c6d9ee42adcb58a94f56d5d63b1758e5b94c479cbcc012baab089a56c48fc1e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-linux-gnu-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "6b7dcdccf1fdcacc4314cd791f9af07ba94cc58e"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "80e415f6f8ffe464a4fe5517df27c76b3f51d1767129b720d844ebc8d4a4d6d2"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-w64-mingw32-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.2"
git-tree-sha1 = "64d9c1f72e6c8be68ce7ab55514fa08a11b4c04b"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "f94460d8bfe97fdff300f9f8e0b0fe30eb7ff5bbf9ebb0e28a8fbc971761bf4f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.powerpc64le-linux-gnu-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "a8446481abd51fbcf86b6580e5db3d84be84383b"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "fc94fdc34a003a757d92f69d9dc717964088be4446d56c6b2057277abf7f652a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-linux-gnu-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "d82b0b068099c13f560bb906feb8f50d4483528b"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "ff7ff0669cfd6930791830afec9a5e1f5a04009860c0e36a12043f31edf0d0fd"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-w64-mingw32-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.3"
git-tree-sha1 = "7b171e773287e00feabf9c245a8454df26ad1802"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "2915410d55e78dc2515e06ccd6bb11c994dcf21d848363c0cedbf7c414b2af1d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.powerpc64le-linux-gnu-cuda+11.3.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "9b1c18a772ad378e259525ba0c01a83a0362f682"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "4498fc8f53959db2c0e8ca411fbf7c974218c2f61ba8943db7708d1548cf45d2"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-linux-gnu-cuda+11.3.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "7c27647697f3b77f1ed2fd9a1a2bd403952d7c48"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "b676a036f3cc108d56ca79940165b8d367e7f791b7b2363ba0defe713df4cf72"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-w64-mingw32-cuda+11.3.tar.gz"
[[CUDA_loader]]
arch = "aarch64"
cuda = "11.4"
git-tree-sha1 = "0aecbe748ec01b572bc8286494f5dde288417514"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "110d28d68ae9bd792331eb72b902bcaa08bfd4b7ba3ae1619cc03acde289b5c1"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.aarch64-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.4"
git-tree-sha1 = "9cdc33e0a7132609e0108449bdaa7f17fcabd812"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "1240cba7ef22b70c937b7fd6e003e6a04295ee071c04cb33ea1091716feccb53"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.powerpc64le-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "5359dff4f087a4354a41ac2eeeb3a0967a5bc9fb"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "f0fc4c1ad31743c18612d99916ebdb7c886ba56cb11fe00701e1330bf3b4a1be"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "b1df3a93c6faf12b5066f381905f75d563584618"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "6465ed87349fc9d27af66f45ca06fd564c78ff8b63d22744f417238005cbc600"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-w64-mingw32-cuda+11.4.tar.gz"
[[CUDA_loader]]
arch = "aarch64"
cuda = "11.5"
git-tree-sha1 = "e414ecf25ac0ab8b19f118a664369c100aa739bf"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "fa1abf51d444cfa98c9250a47ddc7799a2f7e8434e1c5aaaafb0f33549a91645"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.aarch64-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.5"
git-tree-sha1 = "7641effd2313b08352034ae4aa4988756392bd14"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "ebf215d1c0623cf5245b9a31aa1de9600442abd0762bed8694896a30ba0b97b9"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.powerpc64le-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "b03681c6fb1b895303d22171edd146cf897c44ea"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "a218a62c84a15b4f98b0b71a25ddd2b10cfa637412303cf322832f0170c11151"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "ff7aadb27f074c4bc75330ef7e8208ae8caa25c7"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "5e8021faa8f534610661990ec092eee6346be83eef336db03d1a7279210c8c3f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-w64-mingw32-cuda+11.5.tar.gz"
[[CUDA_loader]]
arch = "aarch64"
cuda = "11.6"
git-tree-sha1 = "98d3cd7a26641e0f2d596f8fc18154b03bfcf3d7"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "57bd1befe1a9d6d781598c075af46ded40d08d26a1862a371ff774503fecf869"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.aarch64-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.6"
git-tree-sha1 = "9b935c3a024cb36a8d90b686f65f7e569140c8c4"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "ea3ee870ea139ed28cef130df53fca693462b8bbc0e59a4dd48f35ced7dad7ca"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.powerpc64le-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "6f86c6ce5f06e0d42a996494a39a0b06198ee658"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "e7f8b5f198a23fb46445926454fcf3008f023c6597c8de9e1522d5a69e03014e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "c4508b26bb085d9a2ea276e22c2944fd16acbf60"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "d83da41b21b545a4b1a7fde314143fcf4bca2d48f424a1ba3f38a30b42495beb"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-w64-mingw32-cuda+11.6.tar.gz"
[[CUDA_loader]]
arch = "aarch64"
cuda = "11.7"
git-tree-sha1 = "7e1985f861a432055bd6713ce8663866e6e5ab0f"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "72e707027d37bee980190410d6e62e3b60f24495b45599a4091260b27c101948"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.aarch64-linux-gnu-cuda+11.7.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.7"
git-tree-sha1 = "e3a86fbdde3ee38a1ccdccb09f0a8b1eb0977900"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "f08dfd56891e8045e1db834443e29e236dc4a3720973ebcf7e9e8c6a34222afa"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.powerpc64le-linux-gnu-cuda+11.7.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.7"
git-tree-sha1 = "db7d9369e2332e127d6497588fac063bbf2e7c4f"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "b3bed4ad80134e84b262c41aa067ecc1e36908bc5da9462636ee3c5508c49d2a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-linux-gnu-cuda+11.7.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.7"
git-tree-sha1 = "72395eaf915afb9def4914466dce22e82ac9c72a"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "e5d11545d9d93d33625c05a2139b982d55cebf90ac01ab2580d80ec4cfb85a91"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-w64-mingw32-cuda+11.7.tar.gz"
[[CUDA_loader]]
arch = "aarch64"
cuda = "11.8"
git-tree-sha1 = "44b0a045d405d46dc9f5ad7af5f7bdad3d137875"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "cec0f6c321dd2cb00ff82ddbb65fc8e6d21d15f277872fe67356dc299a5680e6"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.aarch64-linux-gnu-cuda+11.8.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.8"
git-tree-sha1 = "c44d0f3c874bb8f4650e1621537c79dd0fa1edb5"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "85affa0c4b2ce039f45601428c3c4d432a5c5e8487ceea93eaf713bc24d1bb72"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.powerpc64le-linux-gnu-cuda+11.8.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.8"
git-tree-sha1 = "b16cd92510f6afd31e7fc2a7614fb883419ae396"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "1ded0cd43e8029ee2c253e506e2df21da8c1a0a4f341b25de1fe933823b36759"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-linux-gnu-cuda+11.8.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.8"
git-tree-sha1 = "5c0bc670b541bf96e910b493e136787d85137d33"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "15e8cf8bf27daeb0eeba5b4781b79e94e15a55c15a6c6a9ff629be6bbbb3781e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.2+0/CUDA_loader.v0.2.2.x86_64-w64-mingw32-cuda+11.8.tar.gz"
