[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "dece02c5c692d30e57bbbf08c32fb796bb723a53"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "dac5325056c82e9e6dc90d4b6eca7e5b04e9076e585a8f6049edb481e5412bc3"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-apple-darwin-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "100ed6e5e155da971ae666ff07066ad13ec7d41f"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "2d7690495fd0a46bc09b15df1c193fd08dbc159057a8021470202a40ecc77e9b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "120edb04e8793822232aec254fd853c3fd73e0f6"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "ca00216174f4379fc57b2eae037d9bfd7ae6ca124fa3942f06a2584aeb05eca0"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "ba2ce8e3de1877e78178e64d2fa42e19d09f3a4b"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "adb91774c4f28d37739b38c781dda6518394d595881df00b78de50ef23c58d15"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-apple-darwin-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "fb6288928ea05f5d7544cbfe1cae5ce430598637"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "a25831f802821349e23ecaa8486239ba40025db8716b77c2d6d61d8e7ed7a7d0"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "62fd7cb750233da012252650b69d79afe383ff49"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "6a611febdf3991b1c840aa769cd1032c7eab63d8a247a86d355b1ef730424975"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "52b7a2a1a93b057637c056797523d86dbe5e02be"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "104675ab370e448648cbc970c8ea34ccc9de452ca415179034bc1f5cd4c5aa27"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-apple-darwin-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "eaf845385bde55a6e8173696dc97eb5602ac6502"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "3ea08fd4b95298f81aa67ac27a2592caab2cadbce5d482a5857c00a36addeb31"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "5dc75d2507d2886ee5c309d7a9e4c2ecd23d0675"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "49340bbdca0459ae3a50b1154be658eb534c0191a60eb3fe03fccb2028f61187"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "ebf136c22650f0b8d32a6fda896026cc53a06098"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "fee634a68530bc9e54b4f6fffc0351b3b7f1d0251eec678afa8d209a8df190af"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-apple-darwin-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "bf099d60c9c4dd58134edff442aae7247821c5da"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "286e1c3cfdb7cdb7ab3d1f93de4cc3af47a2e87a1661d989ccf937da1a4e2c25"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "a3cdc71ed971c74d70629e78ac6eae95f0187d4a"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "2612bce3052bbda476a630e203f312e521927824cc63ce5b6b7bc5caa73538b5"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "eaa17e7c15ad1a27356fa2e5002f64c3096588e3"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "3e8a56d8645b20a168c296cae95ed88c4af871781ebd85317a9fee3aac5f35ed"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+10.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "f7c05a5c19cc9d2888150993f03b30e2169360f9"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "b6c500a002e8ebff3d48d4465e06c3a0d96765d83fdb052d80da80f915775d83"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+10.2.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.0"
git-tree-sha1 = "53f34a5e5ec49fb8593e912f5eef4dc3a40caf27"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "808154f13416de95fe116017b89849e8aad195ebb250c24af51bfaac2304d1ed"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "c3ee720712fa4156a272c5cdfd1cd3c3151dddff"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "1ecfb9041a4fc129845c89180de02f4edc5f3304ccfba97ceeff7ad509a79141"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "69e5251f686d2774a02bf48aeea04fc1ebe32ada"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "c6503bd795cd5e401a59e69a4eccca108b8b7f8f4f0cb5af362ecffd9c0f6678"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.1"
git-tree-sha1 = "86a9f7a532f5067fa3ee8323cfa669ae86c4753e"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "bd29c231a08ba26e35e58bab5528391d914b819e07fbfd76cdf37ea5af36e360"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "2693b645891b252aa00625d7e0b8c307e4fca584"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "0c544da53c0e14e7c29e0c4e5e039c0178da199c8e2fcb6b34fd3d61e081032b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "6b7dcdccf1fdcacc4314cd791f9af07ba94cc58e"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "cb397467536326a5d06c0cc8618793e3e6e1bed624fec892c4ec266da4e99b64"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.2"
git-tree-sha1 = "19f93631d39bd2f4b9e7e11cc75340e4e21bc0ca"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "b7ee87cd5c86b0b32dcc5e21ac9c5f84966ca8b3cf5303d66ee5524a163c2f99"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "6e3cf2667e777495b267a52c906765aa2638eaae"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "2c49fecc74fc7e08d77632e000a4ed7dfc3583e5592bb77766f93dabee811442"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "d82b0b068099c13f560bb906feb8f50d4483528b"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "3cf5f01713c2094caecae32582020fa577141f2568a8120e1779514b155079eb"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.3"
git-tree-sha1 = "5eb63c9dfac027cdb3bcfb312084505a29246cd1"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "6565aefece1d6fcb350541333591601181bb1bbc1a6a5835bbaedf3c73d328e3"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.3.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "0ed779f9e1d7b0c9905eb5be2c4349d32fbeb050"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "24a8870823e9fe15b37105cc53f3b68a1254ec9367d6827dccfc27330586d833"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.3.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "8c7ad41f40837a2f79bd686a605450e3b8490ca5"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "769603b5cc396b2eb13c5bfaa4c34e6c5e8e8201134692cb9ed4c4f6efaae074"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.3.tar.gz"
[[CUDA_loader]]
arch = "aarch64"
cuda = "11.4"
git-tree-sha1 = "f0c04c3f284ac2a1d16e851239868609b67ea0da"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "cc0eaad0d50833913448a59e898c2ea4e839ab528c5deca31ef4baafc42d2f01"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.aarch64-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.4"
git-tree-sha1 = "2a2ba17109a8c5ece35c67e3d5192cbb9b4058d8"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "c805d70613fc1bdda73640199d2273d9a8423157c8735084f23ae15cc9acbcc6"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "82e04d31e9b4b01b47abe1d89e59f2058f4af1e4"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "29efa06c886238774ffd047c0d438fd61b9dee78a01d4b12949f63f4e466ddf3"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "bb114d805923ac558968d23eda7edd9668ba5047"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "a3feb1d939ab3b7927ddfefd55bb0d6eb6a5b151a527d246d5a68a8bfb42b067"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.4.tar.gz"
[[CUDA_loader]]
arch = "aarch64"
cuda = "11.5"
git-tree-sha1 = "a05da06367254ebc00e7b93aac022077ad848e26"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "ae131f0b6e97dd0a9c8a074652b9327f1eed0352be791ec72d8a0b7d222cdfa3"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.aarch64-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.5"
git-tree-sha1 = "c9048499ab08b382a4f6a5858866520e9fe34cab"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "10f7f21b27a18cfb235f49acda761acd5155c13fa3a0a0e822cfedf45195e306"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "1ada8b4cd8083610e1e41fe9d699f5a451977aeb"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "80a6abea4cfb7f9de5902e4ba8469fd0db7fce4d44b1b06d8c2f49dc9715ae8a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "d451760285a4a4c4b1cc2d27a00d6f0bc4499ab5"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "7b4f1dfaadea28572797afea49c048692bad95ae12e5b843a52fcd9825452818"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+2/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.5.tar.gz"
