[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "dece02c5c692d30e57bbbf08c32fb796bb723a53"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "c4ce9c79de62b525f2c0209fcdd8dca46baa463452e282dbbb794bf480a074d4"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-apple-darwin-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "100ed6e5e155da971ae666ff07066ad13ec7d41f"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "df6cabeaee907307cd54042646c9d29f71bea8da23230d45518c5ebaa3ccaed5"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "120edb04e8793822232aec254fd853c3fd73e0f6"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "cf6387f514859b602de1aa782f7419b0f2f05e2c8d83c87e773b75d7b6e72f3d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "ba2ce8e3de1877e78178e64d2fa42e19d09f3a4b"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "916ba658773256195dfc5b2de591758366a7f34ffe3a8c722ed4fb30267b3353"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-apple-darwin-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "fb6288928ea05f5d7544cbfe1cae5ce430598637"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "0ff733bcbfab223eb33a065ff3adfde8793da739f5b0840bf59ef5568e9688cc"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "62fd7cb750233da012252650b69d79afe383ff49"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "e7a8ed7db047579d1419c98bf6d4e892ce7f51ae3944f8238d89d785eacf5658"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "52b7a2a1a93b057637c056797523d86dbe5e02be"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "3ede9a65c2b31fc00e681580b40e759ebe208d14aeee05d0ecb7bfd416805866"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-apple-darwin-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "eaf845385bde55a6e8173696dc97eb5602ac6502"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "bc2202c66f80bbb824681a71a353d75c5c08745c76088711dfc591e40ba8d7b0"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "5dc75d2507d2886ee5c309d7a9e4c2ecd23d0675"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "86059d089d40a55c03c1d48c99061c501a6e4288032b62a2f56f1a880d50480b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "ebf136c22650f0b8d32a6fda896026cc53a06098"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "817532835bbf874d84c6d974cc45da6d186450dceab1553ab4c13c8af5b90377"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-apple-darwin-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "bf099d60c9c4dd58134edff442aae7247821c5da"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "5190c097b72f6a5c307681532f6f53f284e6255459365b63d4ceb2b5e1f55347"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "a3cdc71ed971c74d70629e78ac6eae95f0187d4a"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "7019c1d97979ebd0be8357a1ecd0c797e5b7c09d000b04546a7a621635ec289b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "eaa17e7c15ad1a27356fa2e5002f64c3096588e3"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "94a246f75dd531ea3f37a68005b23420febf8cab6f6175ac5994e2603f376c2f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+10.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "f7c05a5c19cc9d2888150993f03b30e2169360f9"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "55bfac2eb15729bdddf4f87442526b4e378a465ea8b9e5c08a62d9b9828190fa"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+10.2.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.0"
git-tree-sha1 = "53f34a5e5ec49fb8593e912f5eef4dc3a40caf27"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "229ef821f7bd0c2ec3e5aca16877de7ab40a83a839dfba0ac633f1c3c5cd34d7"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "c3ee720712fa4156a272c5cdfd1cd3c3151dddff"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "324eb011da664dd91ea4fae26c7a737727e90bbb0d29a8d2fef60237005c78fd"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "69e5251f686d2774a02bf48aeea04fc1ebe32ada"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "6013aa4cb0f90ed95526fab5669c3a2bcfa3c4345003d9bcfa76bfae13f75f54"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.1"
git-tree-sha1 = "86a9f7a532f5067fa3ee8323cfa669ae86c4753e"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "c1b09657a4f232ea0a5d6c5db8ddd7aeab2d1ab2c224c3087639cff4b2eafa6c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "2693b645891b252aa00625d7e0b8c307e4fca584"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "79de6f3b75dff9c0892362c8af4656915ef23aa0d717cd45c47a516f25efa93c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "6b7dcdccf1fdcacc4314cd791f9af07ba94cc58e"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "9bfe12f6ceedb246f59e1699a3069ea15ffe176f166f3b3480d8aaee8537d399"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.2"
git-tree-sha1 = "19f93631d39bd2f4b9e7e11cc75340e4e21bc0ca"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "0480b7531042a363749b2cfcfd3ff77670fcda27b3d352e9e9731e66d5068866"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "6e3cf2667e777495b267a52c906765aa2638eaae"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "0e3f5cc1fb07772e1f46e150364798cb195fa3fdc6d1ae9e7b84f29f107e2ce8"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "d82b0b068099c13f560bb906feb8f50d4483528b"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "fedc7ec0f567956a37aec819c2345ead23a396cde8e5307456b2fe8ae6abc7fd"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.3"
git-tree-sha1 = "5eb63c9dfac027cdb3bcfb312084505a29246cd1"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "19199787fd52fe6d72c98d333605d6b299f28c638dfed89e406436ecb1bb7246"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.3.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "0ed779f9e1d7b0c9905eb5be2c4349d32fbeb050"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "53e760945d4cd48c48e1364e85f952d3da385bf7205540ecfb21597cce1f9a14"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.3.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "8c7ad41f40837a2f79bd686a605450e3b8490ca5"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "6d3a635c69272390067fa8bcc252ec47cada1d8e17add46a9136db2c91193776"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.3.tar.gz"
[[CUDA_loader]]
arch = "aarch64"
cuda = "11.4"
git-tree-sha1 = "f0c04c3f284ac2a1d16e851239868609b67ea0da"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "c618b5cb2bae1187a058d8ffd3a5535bc19e795ede660b534b780d592d23d250"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.aarch64-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.4"
git-tree-sha1 = "2a2ba17109a8c5ece35c67e3d5192cbb9b4058d8"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "82d90c16017abd533658e8d5c6858f6c9ab23c748044b5f051dada0069d89968"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "82e04d31e9b4b01b47abe1d89e59f2058f4af1e4"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "eae152c8e5bb63efe1cdcc5f475c3beb5419df03e07be096f4ac0fa42c153e1a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "bb114d805923ac558968d23eda7edd9668ba5047"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "c10976f2c8705776f8834a43db2221cc5dae4e970fab1c466d8a82e70b427906"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+0/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.4.tar.gz"
