[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "dece02c5c692d30e57bbbf08c32fb796bb723a53"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "321f39570b6a94ebb7aab4a86d85153897af8ccb651141da354fa1c6546e24c3"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-apple-darwin-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "0267859e1e69605ad53fc44027db413478bbef47"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "f28fe8152c32b19fb875346fc8fb4e9f94c33a0cc8001000da450f9d71a02267"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "120edb04e8793822232aec254fd853c3fd73e0f6"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "92cc8bbc58a0b776a46e002e089c4086e02423ef355ce6f844d858d7176b767e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "ba2ce8e3de1877e78178e64d2fa42e19d09f3a4b"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "4690605a9fdf410fd19aa808759d9629fbd10de8188c2640137864a7a838742e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-apple-darwin-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "db04ad24a9d0e49d9b9a55fb30e3428b0c1588ca"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "42ed7557934ea1003ff8ecdb1ebe5a0889a8e5aa74f8ef42a83c168f2b7673b5"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "62fd7cb750233da012252650b69d79afe383ff49"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "5a609574e30f3ee3a39db94fdd42fe2529f636598ceeb079ae2d56e16da5970a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "52b7a2a1a93b057637c056797523d86dbe5e02be"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "9d965f2f81e7a15a2d649c212d10cee0a46d5e448563437829f07347c8c7acc9"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-apple-darwin-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "70690cde550c5bac83be1738bc612adb4768def8"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "5492d9cc1689ddddd0ca3e3178ae8898661fd3fec1fbf4ce4bd87e90e3817d76"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "5dc75d2507d2886ee5c309d7a9e4c2ecd23d0675"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "b323813aae0410ddb6c9fc2bbf46113370adab047f1e63ff595579a7026fcc85"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "ebf136c22650f0b8d32a6fda896026cc53a06098"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "9437a93e8081c25e91a8ba58e10158d629d2e590ed3586f8d44dd470024a045d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-apple-darwin-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "0549466c4aab1487f889291765a95d728870df83"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "eee97b9c5cc05ad7c050ecf1932b17e901eb487cc19e5f1762671711a0205402"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "a3cdc71ed971c74d70629e78ac6eae95f0187d4a"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "f750b22ac9839dde530eaf705c438a7419646364fd09c9828dfa64cc48d0e2ff"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "aarch64"
cuda = "10.2"
git-tree-sha1 = "66ae0e2bb7cc22ff985111d231bac42bc52feebe"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "18e4bf777e62add272f2903f8a76dd2b5c064a8b2c94e289bf1ef1404892d24a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.aarch64-linux-gnu-cuda+10.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "59fd9ba6ed7c87a238ddb25482cbab485172b249"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "a6cdfa21e720ae3371ddf6ba726eb6edfc7d1ecd9d5b4c0e3d6198c7772530be"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+10.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "f7c05a5c19cc9d2888150993f03b30e2169360f9"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "816ffbc5b7b502a6838267c595ba690e7899010307e6dfbf36fa57a49169f7cb"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+10.2.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.0"
git-tree-sha1 = "8e6548040ad760f78a668aaad1ea4500e703e42d"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "fe12e56167293b93f49defbcd5ae6b7a4233cefd5d92596ce93fd8c9674f4a21"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "fbcbd3df4c3b626a35d6596cb34c5fb9a1adca29"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "aa828b543ac6c5ade55451839011bf11f279d2d851cac839f31e5e34fbc46403"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "69e5251f686d2774a02bf48aeea04fc1ebe32ada"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "85ea78961135af85fa8badc7033ddfaabfb78744f4e4735d90fad2dcf619b9b9"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.1"
git-tree-sha1 = "9d872cb5c28fe8037248f5cda6d96e8641ade415"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "049cca53a48d535137f81a1a1488dc222e16b9b27cdd09532589a9a6c10a9574"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "afd1b43ce02d76f4f953a73f76931751a047d378"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "40eb5e382b335fe52adefadfa64d6f7c6782d756036139d70db040fc7b03d878"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "6b7dcdccf1fdcacc4314cd791f9af07ba94cc58e"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "68d7a611ff441b8d8f79726eae02f4b96a3c6e24ada20464893099a6e58bd209"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.2"
git-tree-sha1 = "78c193d5e043265ddce577118f1faa2dc7e80c8c"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "9f97938db3eb48a504890c09576061b7853d69d31274da65e587588d9727698a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "0fb33396376d5b161a18db3fb725eab866c2c1d5"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "1b0bb3cc7ef63d9c9b57f35f20daa811097c06efe98824e0196b40c825cce407"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "d82b0b068099c13f560bb906feb8f50d4483528b"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "3c3a2808b418cfac02e083b8c16617addc909dd9850f847e9d87f3110b07eb21"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.3"
git-tree-sha1 = "a54c55f83e3b042321009ce7c938186f12368c9b"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "26f297f524feff883fbffedab73e49b222f7eae5b40c11b1f38ca32eca42e412"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.3.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "5c43fefa32c8d851ee803b67038e736113a0c367"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "4ad9dd6df440cce3b1071c8ccd6d0f144a6fc41b294dce1d0258b80f547a26bd"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.3.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "7c27647697f3b77f1ed2fd9a1a2bd403952d7c48"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "f6d3d3632448aee5a54ddc41af761ebfb769cbd625689749fc9fbd6dfb23079d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.3.tar.gz"
[[CUDA_loader]]
arch = "aarch64"
cuda = "11.4"
git-tree-sha1 = "6f7ca85b54679b0f169df6896fa3fd14e00080d4"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "eec96adfbfd7bfeb1ea7ffd1a6cc0427548f9c3bccbb8dbc7cf32c93d1593d29"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.aarch64-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.4"
git-tree-sha1 = "d45da221660a5cf7d4db67c3e824875686035dc3"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "bc5e66ab1935efa2920cdaf56f179ea7be91d96506da85cebf396f5e97a76938"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "3643872439c1657fb5ff5a62c77297d54f1230b0"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "878879a6360bacb849cbab90df137320fac10a25bad0ba5dc2f19d82d50efae3"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "b1df3a93c6faf12b5066f381905f75d563584618"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "9ef7397e416f6cd48452370b951530b1dd51f365e5c2db473701b996b877c36a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.4.tar.gz"
[[CUDA_loader]]
arch = "aarch64"
cuda = "11.5"
git-tree-sha1 = "d6e2362fc6c14458eddfd3425d40d7a727f04172"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "d5d1f45ec1f79b91a342866483974e84e8acdc55ae9252ecc61fcf9b4aea4198"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.aarch64-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.5"
git-tree-sha1 = "745526aef77d24b67549fa4725c5d8060f1719b1"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "97c79ee6f275e19a731db0ea4eaa0fd77c3e7084190fa3d62f389be0bbeac4aa"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "240d749d36795510ec3468a4c8f029517dfb4982"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "c5b3169ab31588b73f32d6b0fbe00c17f958b8d4ac5ce3fabfba04d1e5c2ecf3"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "ff7aadb27f074c4bc75330ef7e8208ae8caa25c7"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "ea2b7bac0688971aee702152ee57689fe80f98b6d28e9810790c51976e76c2ee"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.5.tar.gz"
[[CUDA_loader]]
arch = "aarch64"
cuda = "11.6"
git-tree-sha1 = "13bdc57e53297fa1eaf73cda01163c1e48ef0bf1"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "85dd422d54927e74ba5e417dd24e420f4a6bbe09148c241ef679d05d9101e412"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.aarch64-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.6"
git-tree-sha1 = "6802e3e0944cedc8e110cc01fbf3421528b0ee33"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "0624f1f00572a8561276f21be4ce9157cf3c3b35e0dbc0c640163a10b09b8454"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "ef45ab8c9ecf2248252097472231043409efbf2e"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "4858207da4e8c6de6d3815b26195d61050837cd353bdbf149076da526d4a6aff"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "c4508b26bb085d9a2ea276e22c2944fd16acbf60"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "34f32d0df097c7d0d75661193ba28380fed67077004b738f23c839cd8692f367"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.6.tar.gz"
[[CUDA_loader]]
arch = "aarch64"
cuda = "11.7"
git-tree-sha1 = "7864902187a2ebdcd22ef7588024b6229c667882"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "5abd13c21828c6df608d970b06e6c39f4c2fdfb26914b2ac1edef6c2677b32a4"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.aarch64-linux-gnu-cuda+11.7.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.7"
git-tree-sha1 = "cc21407ccd10561a92a5b5588f272f690a991b33"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "d1dd08af918e45af97a526f7207fae9663f5bdfec5086ee6a5835900d0a408f8"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.7.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.7"
git-tree-sha1 = "913584335ab836f9781a0325178d0949c193f50b"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "19859a2449c3ceabd5aaed79314b13d40cca8d9ea504fd4cd8691fd604f2f211"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.7.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.7"
git-tree-sha1 = "fd3b38cf5ade69a121c1ed6bc7a0a47f930ac0a1"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "87ed8db4c6f9d76365cc03c8168fe528d095ff5664230bdee098598585beb1a0"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+5/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.7.tar.gz"
