[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "d2cd79d8e110c4db2a17b7ec7b33d896c6d7469f"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "f8aabd32c89cc09a0517d95c8dc3220def74d1b6a15bd6c946e72d3b4413994d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.x86_64-apple-darwin-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "f56c72bf94dac02e372db3eae70a3959bab92931"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "d5e1e3e1a7865dacf2e1a6443ef270fc9131bd10080828457ca04632ffa1238d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "120edb04e8793822232aec254fd853c3fd73e0f6"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "a3c3590edb220ffecc6c68b8d4987b174c6f149c6df8f107ed517168ef626f81"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "32d52e6cf1ef23bfbeaf7dffbe516ce0260b7778"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "dc08b8f132d0ca45f73b1cd4819ca24013958c58ba7fff27e476f5e88a736764"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.x86_64-apple-darwin-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "ef0ed0da8260c507b2130f2d2d82785c5baa7de4"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "45782cc4bbef6bb1ece5cf0e75df6f8eb010686285f80ff55c3252a638ce9b3b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "62fd7cb750233da012252650b69d79afe383ff49"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "b66fad5071faa6e5ec2f7099f46b71ac711493de377a7a5933261c8d4a3be74e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "0e3b996c3953a910ec4665ed272e3842cb3e7a86"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "3bc6c142ca63688d91880a06c786cd8e4f9511c6bab1df1ed3670a0ce275d8c8"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.x86_64-apple-darwin-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "4be664e20fe4887a1f82ac5a8229f68fd16c659a"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "fddd553c94de0c2605a511459b7f8dd4bb2392f3357c32d02f59ad4cf2678319"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "5dc75d2507d2886ee5c309d7a9e4c2ecd23d0675"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "ce27a90a5a573dcb4a970309605160e18447f8fda78d9b12e2d91a4cec2391e7"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "1ee1f01a4e3fc2e0f48fd1acdc1393979daf6e71"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "2d5cd866aba9ea92e153149efe01820ba1245137244f0d4733ce3b82cbd5647f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.x86_64-apple-darwin-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "74c52a7d95eac8b5707d845ea82805c9016d66ec"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "f7f45e15764e4efb5dd45fcf67c7cb3f0ca6f4cab979879fff8965b7fcefe7d5"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "a3cdc71ed971c74d70629e78ac6eae95f0187d4a"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "b5d8afc5f2e9bf4d223b3c90e3d5876cf19e14f86f12f80a9a41b7b0089f8415"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "89bc405feb2b46a05d52a1d00b978a30e3d43c93"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "0a98d593b38b1fe55ff8df196cea3efc94697175be6c99754ec41dc7a699e0f4"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+10.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "f7c05a5c19cc9d2888150993f03b30e2169360f9"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "9cbf6d20ec6fd3497cd48d5ee88974955722cde5730d1cfae935907186428a76"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+10.2.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.0"
git-tree-sha1 = "12b9a943450811dec5fc1e802465bb7a35e74b13"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "2b4adfdbf19d6eb4cc13a772c7f519e70ba1b3e1c73c00ee6837cf5a07806d3f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.powerpc64le-linux-gnu-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "146d26f0d1ea2d9516878edd4eb744abb16eb851"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "e2899c593d19fbe4a77692cc8e177f1f1626dc85206efb550dd41584c422f230"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "69e5251f686d2774a02bf48aeea04fc1ebe32ada"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "63b15deaf70e96f15e840ba22081ea95e0c27272f82c249f18fabb672a85fd4e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.1"
git-tree-sha1 = "f5091063fcb593a00756afad7a1e5470ef56ee97"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "8161827ad95956d8fa9fb4714c5c2e89b1e3e162d1075f09467c503755d6b209"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.powerpc64le-linux-gnu-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "b45b57d8d783dcc6a8ca39518e6cd39b85f12d5f"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "4c1dc40da16da3b9d2aee15a3037c4715d32d907f6cd1fce67e2313fa3b80b59"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "6b7dcdccf1fdcacc4314cd791f9af07ba94cc58e"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "f727e18f66763c578df58f8028df6c18e053d58970ddfc69aef79687842a0757"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.2"
git-tree-sha1 = "2d29a13e4381da68a8c8cec00f1162f0ad4b3d52"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "8818ee036d72c0dddd069b887224ad8226444269adfbc64603c0de78d6694d1b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.powerpc64le-linux-gnu-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "b43f991901ecafe1c6ee23b03ae29637b7a5bda8"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "a3a54b2fdd83b30b438d3e0f0651a2e67ceba09722eadab8fc9fda6c07346842"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "d82b0b068099c13f560bb906feb8f50d4483528b"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "ced06380d315f3bb675659bddbd1a7a955ff45e7971aabde276d78edf1c881c2"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.3"
git-tree-sha1 = "a5078948cf92001fe8d05d52272e8aa12c3bce7e"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "1b68f80435ca0175884bbaf4261a2556f7d157484ef4e54a07d92baefaef9f3b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.powerpc64le-linux-gnu-cuda+11.3.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "300a06a176537de71d95d7f10bf5767f3aa8f009"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "2ffc788852432267087712c2314adfd1fd66a96f57833332c0c81152eed98451"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+11.3.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "b89f1e875e1395458fb170e443e639f71541e074"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "d4c154e4fa6861f20f45c23da1ef772de7d635cf70bb15c2c3e606bc53e3c42a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+2/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+11.3.tar.gz"
