[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "dece02c5c692d30e57bbbf08c32fb796bb723a53"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "ceb4d58044ac574bc73d762b61bd4938ef643ad72b9b3d52a312d78de5bf8782"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-apple-darwin-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "100ed6e5e155da971ae666ff07066ad13ec7d41f"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "99426bf5190c426fad1d641f596eb904f76e822645f95b5fe76f6eb802cac744"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "120edb04e8793822232aec254fd853c3fd73e0f6"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "b31003ee0a6a70df5c082a837c71274f4fb53d9920964eea9c963464c4416244"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "ba2ce8e3de1877e78178e64d2fa42e19d09f3a4b"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "1f3428e7cf77dd7bffee7f782d37714783d50df710d2fc745f9445b2cba1d6e4"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-apple-darwin-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "fb6288928ea05f5d7544cbfe1cae5ce430598637"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "8578cd23b3f4549211a3e0c288234b997e9bb98c4dbc6a3eb443e943208b8057"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "62fd7cb750233da012252650b69d79afe383ff49"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "1c0c529dabcfcd0a094c83254dbf7533cbfc8cec8ce97d448c0db148a443e2c4"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "52b7a2a1a93b057637c056797523d86dbe5e02be"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "961fbe8ae49ea26b475094741e469cd2a61e6e5aa7f7ec4c81b8988b93e8feea"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-apple-darwin-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "eaf845385bde55a6e8173696dc97eb5602ac6502"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "c5cfead8920bf2c1e95246a87018870ff8aeb814f7314b42bc570d2ba16fb97a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "5dc75d2507d2886ee5c309d7a9e4c2ecd23d0675"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "71563d502369ac916d7dafe1eb2c080c4f138f73180452e6cbae794a49da4113"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "ebf136c22650f0b8d32a6fda896026cc53a06098"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "9e9bb908a1b0bd27c28bfbf5985643ff1fbce55c8d82ce4bd8d041a0bf48b371"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-apple-darwin-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "bf099d60c9c4dd58134edff442aae7247821c5da"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "b493567848f864dfd9925ae1bb5cdb8e06d086ffd8640d104a47cc01a09b66d8"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "a3cdc71ed971c74d70629e78ac6eae95f0187d4a"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "76121079c7a07982e3c7576bdfb5e2aefb0c892b5a235b258126f4867b3a6a66"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "eaa17e7c15ad1a27356fa2e5002f64c3096588e3"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "999d5a81f8c586d808d0de35c74d0210bb1a4283d36163fb4fb3b51eaf3cc530"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+10.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "f7c05a5c19cc9d2888150993f03b30e2169360f9"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "adf5a9e2e4f8ceed3ef4d605827d4c72fbef6152d4e53cadd7f1628a69a6b47e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+10.2.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.0"
git-tree-sha1 = "53f34a5e5ec49fb8593e912f5eef4dc3a40caf27"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "b544a8a3ac4424a038b03010b0c82d9caa24ae7ec250710765637b86ce57fa7f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "c3ee720712fa4156a272c5cdfd1cd3c3151dddff"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "8b237ddde796d2fb13cbd56fbb643351d9e86dafaa787e0bc0ada6f141c0c0cc"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "69e5251f686d2774a02bf48aeea04fc1ebe32ada"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "e6dddb70c5509c37abc62ae35fe7b266b74516704aff604d1a5949bfdf94e620"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.1"
git-tree-sha1 = "86a9f7a532f5067fa3ee8323cfa669ae86c4753e"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "9d72fb166fed598a9354f7d5a558c69b8238a650dbd8e00759ec12b281b81873"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "2693b645891b252aa00625d7e0b8c307e4fca584"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "959cbd9e6e5c8b7f6e1ae732c007113903daf957fbc442be35959e8d03e86ddd"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "6b7dcdccf1fdcacc4314cd791f9af07ba94cc58e"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "04b5bf66a1edd4b4f7f06d6dec2ef9f899883907a14f22209d5b476329096862"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.2"
git-tree-sha1 = "19f93631d39bd2f4b9e7e11cc75340e4e21bc0ca"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "03ed1d9aadd3d0cabca90477f23ff43922206e3c0f73191956332314b8c650cb"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "6e3cf2667e777495b267a52c906765aa2638eaae"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "3387e3c58f07c0902e4e2850def250cbf3a558d260a255567d438495093c8998"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "d82b0b068099c13f560bb906feb8f50d4483528b"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "bec1901e44cc6678f403c2045233983e4f04a26fcd0c0329f3b77bab5efdee2b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.3"
git-tree-sha1 = "5eb63c9dfac027cdb3bcfb312084505a29246cd1"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "2f002a4e74972cb462ff19e4ea7a21d8a60a926f6a9ff83259037a211371d57f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.3.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "0ed779f9e1d7b0c9905eb5be2c4349d32fbeb050"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "d9e0f294d5b217ed7c2315db730d4644169f02aafb2c2c3d079857f0ce5456f9"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.3.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "8c7ad41f40837a2f79bd686a605450e3b8490ca5"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "4cdc6446e91d4e8227148252bd79c5b0196d1ed88a537432ff2b65eb5142ae71"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.3.tar.gz"
[[CUDA_loader]]
arch = "aarch64"
cuda = "11.4"
git-tree-sha1 = "f0c04c3f284ac2a1d16e851239868609b67ea0da"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "3e0c6162f7b05cc87e6730cad723f93f4fc99fef2acf0c4165d38f09a4acc55b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.aarch64-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.4"
git-tree-sha1 = "2a2ba17109a8c5ece35c67e3d5192cbb9b4058d8"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "3c4548876a19c307ae6612d62e2f3d6d45330f4f9ae023fe26df62fccf960565"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "82e04d31e9b4b01b47abe1d89e59f2058f4af1e4"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "f8468d609605ff100517c3dd510ef586d24524346479c406f98b1cfa13375094"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "bb114d805923ac558968d23eda7edd9668ba5047"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "d33a3d0d2d8947c3986fe985d2fe5393ba07e7a296855517f7d98c5f16b7feae"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.4.tar.gz"
[[CUDA_loader]]
arch = "aarch64"
cuda = "11.5"
git-tree-sha1 = "a05da06367254ebc00e7b93aac022077ad848e26"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "a1e8aecb2d2e8f2e853a3305d437f8ce0ed0de44187a4bb563e5263f5a71fc46"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.aarch64-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.5"
git-tree-sha1 = "c9048499ab08b382a4f6a5858866520e9fe34cab"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "e12733f80e791427213a4491e4eff867e9b979a34d4762d8c198821f3c6b4b60"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "1ada8b4cd8083610e1e41fe9d699f5a451977aeb"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "604954a334d0e16a096748042f383c162b0543f8a26cd464d8a330a899831086"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "d451760285a4a4c4b1cc2d27a00d6f0bc4499ab5"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "18eb49ecc7e0ff060c010f22d7198066347205549b4ac1b66c905c99af914f97"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.5.tar.gz"
[[CUDA_loader]]
arch = "aarch64"
cuda = "11.6"
git-tree-sha1 = "6e9db6b1466485385ef5f9c5b5603c12b5cb5fc2"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "626221e9837b15e64d6cad3cfb1511ef9a5cd4380d00e747eb2a6ad171d3ba03"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.aarch64-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.6"
git-tree-sha1 = "b1dd5a7e571918735cb65b54bf16ec7318ce1fc7"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "fe9b04a0aa6fb8555c9431b6a54c3386ac236304162354a46aa10cdebf44618c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.powerpc64le-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "7b09e1deca842d1e5467b6f7a8ec5a96d47ae0b4"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "8b7e2eaa8664ef93e5f47d7a90a1028ffb34fdd77be6d691a21e6587bebdb3ea"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "5b2d746447fb85d6eee8c7c2f4780f035b48b9bf"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "1480688f2570bd0b1d2e5691afa1e2f12fe2cac8b1e81e12ca536bf9a61a298f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.2.1+3/CUDA_loader.v0.2.1.x86_64-w64-mingw32-cuda+11.6.tar.gz"
