[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "d2cd79d8e110c4db2a17b7ec7b33d896c6d7469f"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "59bb66798f3a6ef752c7b4a6f117ed18c1e93e1e7cfb2e00e469eb4c17aead06"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.x86_64-apple-darwin-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "f56c72bf94dac02e372db3eae70a3959bab92931"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "8e1a0263f6c1b73e935e4c3acbe4d50ada5214ccd754c3b69f6ad0d0741f8c1d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "120edb04e8793822232aec254fd853c3fd73e0f6"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "1efc5e2112ac74f1c5079ba33ee4259e660140c247d0553f8ca934d0dc68427e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "32d52e6cf1ef23bfbeaf7dffbe516ce0260b7778"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "823d65ebf3df0d71509f2fc607872dfcf11c098185f749b9188d874bb54fbe24"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.x86_64-apple-darwin-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "ef0ed0da8260c507b2130f2d2d82785c5baa7de4"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "13aa18008a0897f24c7364ec1e3f8d5f138339b35cede4072873b169852c3ecc"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "62fd7cb750233da012252650b69d79afe383ff49"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "22021c854bd614c563895ec38a158e1fe3d12508fab17eb6e622a5cc4122f78b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "0e3b996c3953a910ec4665ed272e3842cb3e7a86"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "803797e001fe069f438fd22bbf02c559588af6e8453671944ae80f2f0d25b47e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.x86_64-apple-darwin-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "4be664e20fe4887a1f82ac5a8229f68fd16c659a"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "34f471807ba448aa0a7de8b492acdf3c8c870a9c6a459571e0792ac521251913"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "5dc75d2507d2886ee5c309d7a9e4c2ecd23d0675"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "96f16a7c1c796a7027272b7dae40b2cb06245a1eba735afe4fb18d20b129437d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "1ee1f01a4e3fc2e0f48fd1acdc1393979daf6e71"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "c1173748e64ece7e929a99fac43642426708b06e89af9b54160d7ac77a0b92c9"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.x86_64-apple-darwin-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "74c52a7d95eac8b5707d845ea82805c9016d66ec"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "9c9cd7198a4539223323ecb2446415eda8ffdbca41164b9bdbf98e012f4930d5"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "a3cdc71ed971c74d70629e78ac6eae95f0187d4a"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "f7c61df6cc695b0bd83f6f1c8b5e13ee00c51c2a97e7839105aa24eb9b4a4f25"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "89bc405feb2b46a05d52a1d00b978a30e3d43c93"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "dfc69a54f9cc5de39db8f4b353985948fa5c82617bbe1dd7886e5e513c2c1538"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+10.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "f7c05a5c19cc9d2888150993f03b30e2169360f9"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "e864a76f8fd5fc02f7426a3b1937cbb6637bce057d0a59fb5d81b49be5cd5be7"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+10.2.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.0"
git-tree-sha1 = "12b9a943450811dec5fc1e802465bb7a35e74b13"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "415a45cd43945ca9cf166b70027bfe66b5ab73f26b5a6692dc3834b14167c266"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.powerpc64le-linux-gnu-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "146d26f0d1ea2d9516878edd4eb744abb16eb851"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "4f392263ef07adc2e58a6227afc2e31c221a07d2085d6b168115945b2bd0c906"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "69e5251f686d2774a02bf48aeea04fc1ebe32ada"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "97475a7f76caa38a5697f7e4d2a1c9c5792dc7468560c26f97994bb153d77851"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.1"
git-tree-sha1 = "f5091063fcb593a00756afad7a1e5470ef56ee97"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "bd511f923ce4a93829bc1ae06d71a94642eccd49e18c1242ea1b14a2a59a28d7"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.powerpc64le-linux-gnu-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "b45b57d8d783dcc6a8ca39518e6cd39b85f12d5f"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "0ebb03fddf6818dd17d6e179e3bdf406276f0b843b72eed647a4e928b05ccce7"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "6b7dcdccf1fdcacc4314cd791f9af07ba94cc58e"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "ec23fc40bbdbb6d7ccd3961a4ae02855b9ebe847e66230a28c0f669d5e98a2a9"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.2"
git-tree-sha1 = "2d29a13e4381da68a8c8cec00f1162f0ad4b3d52"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "3ea23783a485e1f736a92265b8e6f762cbe1fb9549836938c8c9228abfd10773"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.powerpc64le-linux-gnu-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "b43f991901ecafe1c6ee23b03ae29637b7a5bda8"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "8e608c6cd00027a235bad3f38df09d02e22a3060288251a0d747ba1d428df26f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "d82b0b068099c13f560bb906feb8f50d4483528b"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "94ff813266d4180a815704c4b905859813e64802d1b01bf4f83b2f3a77dfb608"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.3"
git-tree-sha1 = "a5078948cf92001fe8d05d52272e8aa12c3bce7e"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "a75adf5a21a0f21c615f76576c49d4557339cd8097decfcfcf0c3c134a2b326e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.powerpc64le-linux-gnu-cuda+11.3.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "300a06a176537de71d95d7f10bf5767f3aa8f009"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "36ed7f1e1739d22084d68cb51c668cae7412a9416dca9beb452b19263ff23607"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+11.3.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "b89f1e875e1395458fb170e443e639f71541e074"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "2a58a1dc97c3fc02e7dba042259745219901e8829c43c4ff4a579917c724029c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+3/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+11.3.tar.gz"
