[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "63dcd6776fe994c058760c0a8c698b0c7f73094d"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "3fa3591a837fc88cc2e46548f74f754993cfff7422c7b8d14bb44fc87bdea1a4"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.x86_64-apple-darwin-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "562390c67d710ded742f53d92e39b3b9f418ca9e"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "6af7c7d66af2ffaf380b9f8a4bbd32d111225f2573757e2f3370931a2afad70f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.0"
git-tree-sha1 = "765884b0b2eb28ae8949cd87dc0cbb249a673ea0"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "9d64e7f973c3c76501c89b035fb8fcdc05f54b085bfb4a29cc152da871aa65fe"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+9.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "ae9f23bc83478947b2a98cda090a1abfd2f91cf4"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "4b57daf09e7aca01f9d4bd1ddab85863c1fc52ae15863eead7547b83b25cc264"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.x86_64-apple-darwin-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "e5ee257bba6f9dab66080ac824d8eee02e0785d6"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "4e3ff05a0f7c656b32bdaa829f2197ffdae6a1bc4f338ed773d5d900f6c28ec7"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "9.2"
git-tree-sha1 = "4cf049b0e0d3b3a60d9b20c869046b0e0e20a3de"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "7f108675b523e0b830418e226aefa86e1b2caae82113c89c92ee9d4271c8d736"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+9.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "5e2a256696512818e4d7860da4370c55a05b7a7f"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "dcea5de9306e92be6623aecdba30d09e2e30cdd12e93814ddcf1e8fe5cce0fd9"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.x86_64-apple-darwin-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "778bd2884effbb6b9b21e7301ba65e22ee83ead8"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "36df5bfb10ca635052244a16eb89807d35b6d0a63be79f61da665567c99cb9ca"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.0"
git-tree-sha1 = "6d6f90bf152829ac1c4972163099a43c83e362e1"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "26e20c3125acf9b4ed977760ede991b09af3dc8c7fd11d574bffbafe93e9cd7a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+10.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "3b7bd4542d040e258e305ffb5ae317fa76733da1"
lazy = true
os = "macos"

    [[CUDA_loader.download]]
    sha256 = "528eb500e85cbf3784f365dc30c3fdae896a74db773b5bebd84bb0d92b3f3e18"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.x86_64-apple-darwin-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "9f28b71429419dd41fc66dd9b690d546c85a78c2"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "5f3bc1f6323ea2a28b5ab34d649c607cbea5ce797b7be805f40a5f5c67c78e75"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.1"
git-tree-sha1 = "9aacfe32437841154cb3627cc914fa98868ae39f"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "06fd35b8e161a1b92be6261e1579a0d8882148206a7683a98faa1f8c50b3f306"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+10.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "8b671320f9368e88a040dcae03bf01e9d813e48f"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "d872797a72deecfbc286a5ef6f5afbb78212756f0769f9d8a8b5d6fbf6499656"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+10.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "4ace71e61290e56f9dd079803bf710b706fb6568"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "e725db93c64ba9f21d618089843050157b7345ba8d2ff34220fffdd39e4dd03c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+10.2.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.0"
git-tree-sha1 = "2bc92bc8fe2755d3b94c877413099d6f28992c77"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "8772f5496e2ccf0f7ac0ed42c68a250da8d3d82c022afc7652e3ec0452a354e2"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.powerpc64le-linux-gnu-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "3c7506db5d2322995ea28eea95a1ee0672cbc140"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "4802d31bf0f2cb305407c370a0c985d54fa7037824230c520d0931720ee16f5c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "578db95e79117cda9d61e7a9e48df0d6b9b1041e"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "e0d8c94039c1eb223d3ba799af96d36a55789a3365385c20d30ad1a2405fcad9"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+11.0.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.1"
git-tree-sha1 = "3a3889762a3c2e8ccf58bfc39c5438754c1dc053"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "52c1f4c41dd714cc444f0fe8c434e02d28b46d4fc01ef1f2fc8d22986aa3ca33"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.powerpc64le-linux-gnu-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "71d4e24644296aa2af54bab5f051b4585b99facd"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "177986f076a7d989a2f283b37cbf7084eab16fa1a720218423cd4133643adb35"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "db3448a9b65319655896015b366e028d9216cbd2"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "123250bb028a1834739e63b2114787bbb5e55e71f61d9325e37222644763ca51"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+11.1.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.2"
git-tree-sha1 = "5225f06b525538f4e86133f5c47e8afcd9680f66"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "715de29f3d917a99ac6da7bfaafa52fa2de71e82bb7d31d960cfcf0499e8e562"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.powerpc64le-linux-gnu-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "58b6c185386a2f397c2daec2f2e24d41221083c5"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "c0858ef64e3cd2235f4e3e1ebe5e07d357d2dd55b20845612a506814fa9f27cf"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "59bf3b37a9cd7009f54d04ce92cc1ab46aa85cc9"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "00342f8647379e9c02a1d4ce5fabbaf0e42554de52fc6b8869adb49e73792b1b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+11.2.tar.gz"
[[CUDA_loader]]
arch = "powerpc64le"
cuda = "11.3"
git-tree-sha1 = "0f0488b81cac4c86f25d05c8f4c281bff1f761ac"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "3d2d514fd7a1b125c2a0f5b895ac7f98e180fa821b1bc80fa7c8300797084dde"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.powerpc64le-linux-gnu-cuda+11.3.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "d90103bfc06085e90c69bccc59c894e1ea6262db"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_loader.download]]
    sha256 = "0948b85d5cf0f9e6ea7d7656336a70970afdc501a064eac6a3a7c9c6820866f4"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.x86_64-linux-gnu-cuda+11.3.tar.gz"
[[CUDA_loader]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "bd1a1ca366918d90b583b28856a86e1027045b4a"
lazy = true
os = "windows"

    [[CUDA_loader.download]]
    sha256 = "c6fafa836308620ada7ac718b22bcf385248903f32e758c7afbb3950550f648c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/releases/download/CUDA_loader-v0.1.0+1/CUDA_loader.v0.1.0.x86_64-w64-mingw32-cuda+11.3.tar.gz"
